[package]
name = "rcs3ud"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-sdk-s3 = "1.97.0"
sipper = "0.1.0"
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["fs"] }

[dev-dependencies]
aws-config = "1.8.2"
tokio = { version = "1.46.1", features = ["full"] }
