[package]
name = "rcs3ud_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.8.5"
aws-sdk-s3 = "1.103.0"
clap = { version = "4.5.45", features = ["derive"] }
rcs3ud = { path = "../" }
ron = "0.10.1"
sipper = "0.1.0"
tokio = { version = "1.47.1", features = ["full"] }
